@tool
# GENERATED by scripts/gen_object_event_sprites.py — do not edit by hand.
# Source: src/data/object_events/*.h (a four-file join; see the script).
class_name ObjectEventGraphics
extends RefCounted

const SHEET_DIR := "res://assets/sprites/overworld/object_events/"
const FX_DIR := "res://assets/sprites/overworld/field_effects/"

## ANIM_STD_FACE_* -> which frame of the sheet to draw.
##
## EAST has no frame of its own: sAnim_FaceEast is
## ANIMCMD_FRAME(2, .., .hFlip = TRUE), so a renderer draws WEST mirrored.
## Getting this wrong is invisible for symmetric sprites and obvious for
## every character carrying something.
const FACE_FRAME := {
	"SOUTH": 0,
	"NORTH": 1,
	"WEST": 2,
	"EAST": 2,
}

## True when EAST must be drawn as a horizontally flipped WEST.
const EAST_IS_MIRRORED_WEST := true

## The two step frames per facing, for the walk cycle.
##
## From sAnim_GoSouth/North/West/East. The cycle each one runs is
## FRAME(stepA) FRAME(idle) FRAME(stepB) FRAME(idle), looping — so the
## resting frame is part of the walk, not just what precedes it, and a
## renderer that alternates stepA/stepB alone drops half the animation.
## EAST reuses WEST's pair mirrored, exactly as its idle frame does.
const STEP_FRAME := {
	"SOUTH": [3, 4],
	"NORTH": [5, 6],
	"WEST": [7, 8],
	"EAST": [7, 8],
}

## Order the four cycle entries are played in: step, rest, step, rest.
## Indexes into [stepA, idle, stepB, idle] as built by WalkAnim.
const WALK_CYCLE_LEN := 4

## Ticks each cycle entry is held, by movement speed (the second
## argument of each ANIMCMD_FRAME).
##
## ⚠ There is NO GoSlow* anim in source — the standard table is
## FACE / GO / GO_FAST / GO_FASTER / GO_FASTEST only. A slow walk reuses
## the NORMAL anim, so its 32 movement frames play FOUR cycle entries
## rather than two stretched ones. That asymmetry is real: a slow walk
## shows more foot movement per tile, not slower foot movement.
const ANIM_TICKS_NORMAL := 8
const ANIM_TICKS_FAST := 4
const ANIM_TICKS_FASTER := 2

## [M27E E2] The RUN cycle's own frames, from sAnim_Run*Frlg.
##
## ⚠ RAW indices into the *_surf_run sheet, NOT the pic-table indices
## source's anims quote. Source stitches 11 frames of that file onto the
## walking sheet and calls them 9-19; this project reads the file itself,
## so every index is 6 lower (its frames 0-2 are the SURF poses).
##
## The neutral pose is a RUN-specific frame, NOT the standing FACE frame
## the walk cycle rests on -- a runner never shows its standing sprite.
const RUN_IDLE_FRAME := {
	"SOUTH": 3,
	"NORTH": 6,
	"WEST": 9,
	"EAST": 9,
}

## The two leg frames per facing, from the same four anims.
const RUN_STEP_FRAME := {
	"SOUTH": [4, 5],
	"NORTH": [7, 8],
	"WEST": [10, 11],
	"EAST": [10, 11],
}

## Ticks per cycle entry: [neutral, legA, neutral, legB].
##
## ⚠ UNEVEN, unlike every walk anim in this file -- source holds the
## neutral pose 5 frames and each leg 3. Averaging them to 4 would run at
## the right overall cadence and read wrong, because the leg would be up
## as long as the body is level.
const RUN_TICKS := [5, 3, 5, 3]

## RAW frames a sheet needs to hold the run cycle (indices 0-11).
##
## ⚠ Compare against the SHEET's real width, never a graphics id's own
## `frames`: FRAME_OVERRIDES reports 3 for the surf ids, so an id-based
## check would refuse the very sheet the run frames live on.
const MIN_RAW_FRAMES_TO_RUN := 12

## A sheet needs all nine frames to hold a walk cycle. 136 of the 385
## resolved ids do; 70 carry only the three facing frames (signs, static
## props) and 96 carry a single frame. Those must draw their idle frame
## and never index past it.
const MIN_FRAMES_TO_ANIMATE := 9

## Source's own fallback for an id it cannot resolve
## (GetObjectEventGraphicsInfo: `graphicsId = OBJ_EVENT_GFX_NINJA_BOY`).
## A real, visible sprite rather than an invented placeholder — so a hole
## is obvious, and M27G's VAR_* lookup slots in ahead of it with nothing
## to undo.
const FALLBACK_ID := "OBJ_EVENT_GFX_NINJA_BOY"

## graphics_id -> { sheet, w, h, frames }.
##
## Sheets are HORIZONTAL strips: frame N is at x = N * w, y = 0.
## Measured across all 385 resolved ids — 384 horizontal, 0 vertical.
const BY_ID := {
	"OBJ_EVENT_GFX_AGATHA": {"sheet": "people_agatha", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_ANABEL": {"sheet": "people_frontier_brains_anabel", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_APRICORN_TREE": {"sheet": "misc_apricorn_tree", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_AQUA_MEMBER_F": {"sheet": "people_team_aqua_aqua_member_f", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_AQUA_MEMBER_M": {"sheet": "people_team_aqua_aqua_member_m", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_ARCHIE": {"sheet": "people_team_aqua_archie", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_ARTICUNO": {"sheet": "pokemon_old_articuno", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_ARTIST": {"sheet": "people_artist", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_AZUMARILL": {"sheet": "pokemon_old_azumarill", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_AZURILL": {"sheet": "pokemon_old_azurill", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_AZURILL_DOLL": {"sheet": "dolls_azurill_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_BALDING_MAN": {"sheet": "people_balding_man", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_BALL_CUSHION": {"sheet": "cushions_ball_cushion", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_BALTOY_DOLL": {"sheet": "dolls_baltoy_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_BARD": {"sheet": "people_mauville_old_man_1", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_BEAUTY": {"sheet": "people_beauty", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_BEAUTY_FRLG": {"sheet": "people_beauty_frlg", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_BERRY_TREE": {"sheet": "berry_trees_dirt_pile", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES": {"sheet": "berry_trees_dirt_pile", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES": {"sheet": "berry_trees_dirt_pile", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL": {"sheet": "dolls_big_blastoise_doll", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL": {"sheet": "dolls_big_charizard_doll", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_BIG_LAPRAS_DOLL": {"sheet": "dolls_big_lapras_doll", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_BIG_REGICE_DOLL": {"sheet": "dolls_big_regice_doll", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_BIG_REGIROCK_DOLL": {"sheet": "dolls_big_regirock_doll", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL": {"sheet": "dolls_big_registeel_doll", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_BIG_RHYDON_DOLL": {"sheet": "dolls_big_rhydon_doll", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_BIG_SNORLAX_DOLL": {"sheet": "dolls_big_snorlax_doll", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL": {"sheet": "dolls_big_venusaur_doll", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_BIG_WAILMER_DOLL": {"sheet": "dolls_big_wailmer_doll", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_BIKER": {"sheet": "people_biker", "w": 32, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_BILL": {"sheet": "people_bill", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_BIRCHS_BAG": {"sheet": "misc_birchs_bag", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_BLACK_BELT": {"sheet": "people_black_belt", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_BLACK_BELT_FRLG": {"sheet": "people_black_belt_frlg", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_BLAINE": {"sheet": "people_blaine", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_BLUE": {"sheet": "people_blue", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_BOY": {"sheet": "people_boy", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_BOY_1": {"sheet": "people_boy_1", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_BOY_2": {"sheet": "people_boy_2", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_BOY_3": {"sheet": "people_boy_3", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_BRANDON": {"sheet": "people_frontier_brains_brandon", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_BRAWLY": {"sheet": "people_gym_leaders_brawly", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_BREAKABLE_ROCK": {"sheet": "misc_breakable_rock", "w": 16, "h": 16, "frames": 4},
	"OBJ_EVENT_GFX_BREAKABLE_ROCK_FRLG": {"sheet": "misc_breakable_rock_frlg", "w": 16, "h": 16, "frames": 4},
	"OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE": {"sheet": "people_brendan_acro_bike", "w": 32, "h": 32, "frames": 27},
	"OBJ_EVENT_GFX_BRENDAN_DECORATING": {"sheet": "people_brendan_decorating", "w": 16, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE": {"sheet": "people_brendan_field_move", "w": 32, "h": 32, "frames": 5},
	"OBJ_EVENT_GFX_BRENDAN_FISHING": {"sheet": "people_brendan_fishing", "w": 32, "h": 32, "frames": 12},
	"OBJ_EVENT_GFX_BRENDAN_MACH_BIKE": {"sheet": "people_brendan_mach_bike", "w": 32, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_BRENDAN_NORMAL": {"sheet": "people_brendan_walking", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_BRENDAN_SURFING": {"sheet": "people_brendan_surfing", "w": 32, "h": 32, "frames": 6},
	"OBJ_EVENT_GFX_BRENDAN_UNDERWATER": {"sheet": "people_brendan_underwater", "w": 32, "h": 32, "frames": 4},
	"OBJ_EVENT_GFX_BRENDAN_WATERING": {"sheet": "people_brendan_watering", "w": 32, "h": 32, "frames": 6},
	"OBJ_EVENT_GFX_BROCK": {"sheet": "people_brock", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_BRUNO": {"sheet": "people_bruno", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_BUG_CATCHER": {"sheet": "people_bug_catcher", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_BUG_CATCHER_FRLG": {"sheet": "people_bug_catcher_frlg", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_CABLE_CAR": {"sheet": "misc_cable_car", "w": 64, "h": 64, "frames": 1},
	"OBJ_EVENT_GFX_CABLE_CLUB_RECEPTIONIST": {"sheet": "people_cable_club_receptionist", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_CAMERAMAN": {"sheet": "people_cameraman", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_CAMPER": {"sheet": "people_camper", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_CAMPER_FRLG": {"sheet": "people_camper_frlg", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_CAPTAIN": {"sheet": "people_captain", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_CELEBI": {"sheet": "pokemon_old_celebi", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_CELIO": {"sheet": "people_celio", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_CHANNELER": {"sheet": "people_channeler", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_CHANSEY": {"sheet": "pokemon_old_chansey", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_CHEF": {"sheet": "people_chef", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_CHIKORITA_DOLL": {"sheet": "dolls_chikorita_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_CLEFAIRY": {"sheet": "pokemon_old_clefairy", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_CLEFAIRY_DOLL": {"sheet": "dolls_clefairy_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_CLERK": {"sheet": "people_clerk", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_CLIPBOARD": {"sheet": "misc_clipboard", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_CONTEST_JUDGE": {"sheet": "people_contest_judge", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_COOK": {"sheet": "people_cook", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_COOLTRAINER_F": {"sheet": "people_cooltrainer_f", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_COOLTRAINER_M": {"sheet": "people_cooltrainer_m", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_CRUSH_GIRL": {"sheet": "people_crush_girl", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_CUBONE": {"sheet": "pokemon_old_cubone", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_CUTTABLE_TREE": {"sheet": "misc_cuttable_tree", "w": 16, "h": 16, "frames": 4},
	"OBJ_EVENT_GFX_CUTTABLE_TREE_FRLG": {"sheet": "misc_cuttable_tree_frlg", "w": 16, "h": 16, "frames": 4},
	"OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F": {"sheet": "people_cycling_triathlete_f", "w": 32, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M": {"sheet": "people_cycling_triathlete_m", "w": 32, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_CYNDAQUIL_DOLL": {"sheet": "dolls_cyndaquil_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_DAISY": {"sheet": "people_daisy", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_DEOXYS": {"sheet": "pokemon_old_deoxys", "w": 32, "h": 32, "frames": 2},
	"OBJ_EVENT_GFX_DEOXYS_A": {"sheet": "pokemon_old_deoxys_a", "w": 32, "h": 32, "frames": 2},
	"OBJ_EVENT_GFX_DEOXYS_D": {"sheet": "pokemon_old_deoxys_d", "w": 32, "h": 32, "frames": 2},
	"OBJ_EVENT_GFX_DEOXYS_N": {"sheet": "pokemon_old_deoxys_n", "w": 32, "h": 32, "frames": 2},
	"OBJ_EVENT_GFX_DEOXYS_TRIANGLE": {"sheet": "misc_birth_island_stone", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_DEVON_EMPLOYEE": {"sheet": "people_devon_employee", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_DIAMOND_CUSHION": {"sheet": "cushions_diamond_cushion", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_DITTO_DOLL": {"sheet": "dolls_ditto_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_DODUO": {"sheet": "pokemon_old_doduo", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_DRAKE": {"sheet": "people_elite_four_drake", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_DUSCLOPS": {"sheet": "pokemon_old_dusclops", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_DUSKULL_DOLL": {"sheet": "dolls_duskull_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_ENTEI": {"sheet": "pokemon_old_entei", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_ERIKA": {"sheet": "people_erika", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_EXPERT_F": {"sheet": "people_expert_f", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_EXPERT_M": {"sheet": "people_expert_m", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_FAT_MAN": {"sheet": "people_fat_man", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_FAT_MAN_FRLG": {"sheet": "people_fat_man_frlg", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_FEAROW": {"sheet": "pokemon_old_fearow", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_FIRE_CUSHION": {"sheet": "cushions_fire_cushion", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_FISHER": {"sheet": "people_fisher", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_FISHERMAN": {"sheet": "people_fisherman", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_FLANNERY": {"sheet": "people_gym_leaders_flannery", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_FOSSIL": {"sheet": "misc_fossil", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_FOSSIL_FRLG": {"sheet": "misc_fossil_frlg", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_GAMEBOY_KID": {"sheet": "people_gameboy_kid", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_GBA_KID": {"sheet": "people_gba_kid", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_GENTLEMAN": {"sheet": "people_gentleman", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_GENTLEMAN_FRLG": {"sheet": "people_gentleman_frlg", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_GIOVANNI": {"sheet": "people_giovanni", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_GIRL_1": {"sheet": "people_girl_1", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_GIRL_2": {"sheet": "people_girl_2", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_GIRL_3": {"sheet": "people_girl_3", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_GLACIA": {"sheet": "people_elite_four_glacia", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_GRASS_CUSHION": {"sheet": "cushions_grass_cushion", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_GREEN_BIKE": {"sheet": "people_leaf_green_bike", "w": 32, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_GREEN_FIELD_MOVE": {"sheet": "people_leaf_green_item", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_GREEN_FISH": {"sheet": "people_leaf_green_fish", "w": 32, "h": 32, "frames": 12},
	"OBJ_EVENT_GFX_GREEN_NORMAL": {"sheet": "people_leaf_green_normal", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_GREEN_SURF": {"sheet": "people_leaf_green_surf_run", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_GREEN_VS_SEEKER": {"sheet": "people_leaf_green_item", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_GREEN_VS_SEEKER_BIKE": {"sheet": "people_leaf_green_vs_seeker_bike", "w": 32, "h": 32, "frames": 6},
	"OBJ_EVENT_GFX_GRETA": {"sheet": "people_frontier_brains_greta", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_GROUDON_ASLEEP": {"sheet": "pokemon_old_groudon", "w": 32, "h": 32, "frames": 4},
	"OBJ_EVENT_GFX_GROUDON_FRONT": {"sheet": "pokemon_old_groudon", "w": 32, "h": 32, "frames": 4},
	"OBJ_EVENT_GFX_GROUDON_SIDE": {"sheet": "pokemon_old_groudon", "w": 32, "h": 32, "frames": 4},
	"OBJ_EVENT_GFX_GULPIN_DOLL": {"sheet": "dolls_gulpin_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_GYM_GUY": {"sheet": "people_gym_guy", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_GYM_SIGN": {"sheet": "misc_gym_sign", "w": 16, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_HEX_MANIAC": {"sheet": "people_hex_maniac", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_HIKER": {"sheet": "people_hiker", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_HIKER_FRLG": {"sheet": "people_hiker_frlg", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_HOOH": {"sheet": "pokemon_old_ho_oh", "w": 32, "h": 32, "frames": 2},
	"OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN": {"sheet": "people_hot_springs_old_woman", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_ITEM_BALL": {"sheet": "misc_ball_poke", "w": 16, "h": 32, "frames": 5},
	"OBJ_EVENT_GFX_JIGGLYPUFF": {"sheet": "pokemon_old_jigglypuff", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_JIGGLYPUFF_DOLL": {"sheet": "dolls_jigglypuff_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_JUAN": {"sheet": "people_gym_leaders_juan", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_KABUTO": {"sheet": "pokemon_old_kabuto", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_KANGASKHAN": {"sheet": "pokemon_old_kangaskhan", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_KECLEON": {"sheet": "pokemon_old_kecleon", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW": {"sheet": "pokemon_old_kecleon", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_KECLEON_DOLL": {"sheet": "dolls_kecleon_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_KIRLIA": {"sheet": "pokemon_old_kirlia", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_KISS_CUSHION": {"sheet": "cushions_kiss_cushion", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_KOGA": {"sheet": "people_koga", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_KYOGRE_ASLEEP": {"sheet": "pokemon_old_kyogre", "w": 32, "h": 32, "frames": 4},
	"OBJ_EVENT_GFX_KYOGRE_FRONT": {"sheet": "pokemon_old_kyogre", "w": 32, "h": 32, "frames": 4},
	"OBJ_EVENT_GFX_KYOGRE_SIDE": {"sheet": "pokemon_old_kyogre", "w": 32, "h": 32, "frames": 4},
	"OBJ_EVENT_GFX_LANCE": {"sheet": "people_lance", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_LAPRAS": {"sheet": "pokemon_old_lapras", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_LAPRAS_DOLL": {"sheet": "misc_lapras_doll", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_LASS": {"sheet": "people_lass", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_LASS_FRLG": {"sheet": "people_lass_frlg", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_LATIAS": {"sheet": "pokemon_old_latias_latios", "w": 32, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_LATIOS": {"sheet": "pokemon_old_latias_latios", "w": 32, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_LEAF": {"sheet": "people_leaf", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_LINK_BRENDAN": {"sheet": "people_brendan_walking", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_LINK_MAY": {"sheet": "people_may_walking", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_LINK_RECEPTIONIST": {"sheet": "people_link_receptionist", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_LINK_RS_BRENDAN": {"sheet": "people_ruby_sapphire_brendan_walking", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_LINK_RS_MAY": {"sheet": "people_ruby_sapphire_may_walking", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_LITTLE_BOY": {"sheet": "people_little_boy", "w": 16, "h": 16, "frames": 9},
	"OBJ_EVENT_GFX_LITTLE_BOY_3": {"sheet": "people_rs_little_boy", "w": 16, "h": 16, "frames": 9},
	"OBJ_EVENT_GFX_LITTLE_BOY_FRLG": {"sheet": "people_little_boy_frlg", "w": 16, "h": 16, "frames": 9},
	"OBJ_EVENT_GFX_LITTLE_GIRL": {"sheet": "people_little_girl", "w": 16, "h": 16, "frames": 9},
	"OBJ_EVENT_GFX_LITTLE_GIRL_FRLG": {"sheet": "people_little_girl_frlg", "w": 16, "h": 16, "frames": 10},
	"OBJ_EVENT_GFX_LIZA": {"sheet": "people_gym_leaders_liza", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_LORELEI": {"sheet": "people_lorelei", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_LOTAD_DOLL": {"sheet": "dolls_lotad_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_LT_SURGE": {"sheet": "people_lt_surge", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_LUCY": {"sheet": "people_frontier_brains_lucy", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_LUGIA": {"sheet": "pokemon_old_lugia", "w": 32, "h": 32, "frames": 2},
	"OBJ_EVENT_GFX_MACHOKE": {"sheet": "pokemon_old_machoke", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_MACHOP": {"sheet": "pokemon_old_machop", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_MAGMA_MEMBER_F": {"sheet": "people_team_magma_magma_member_f", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_MAGMA_MEMBER_M": {"sheet": "people_team_magma_magma_member_m", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_MAN": {"sheet": "people_man", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_MANIAC": {"sheet": "people_maniac", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_MAN_1": {"sheet": "people_man_1", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_MAN_2": {"sheet": "people_man_2", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_MAN_3": {"sheet": "people_man_3", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_MAN_4": {"sheet": "people_man_4", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_MAN_5": {"sheet": "people_man_5", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_MARILL_DOLL": {"sheet": "dolls_marill_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_MART_EMPLOYEE": {"sheet": "people_mart_employee", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_MAXIE": {"sheet": "people_team_magma_maxie", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_MAY_ACRO_BIKE": {"sheet": "people_may_acro_bike", "w": 32, "h": 32, "frames": 27},
	"OBJ_EVENT_GFX_MAY_DECORATING": {"sheet": "people_may_decorating", "w": 16, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_MAY_FIELD_MOVE": {"sheet": "people_may_field_move", "w": 32, "h": 32, "frames": 5},
	"OBJ_EVENT_GFX_MAY_FISHING": {"sheet": "people_may_fishing", "w": 32, "h": 32, "frames": 12},
	"OBJ_EVENT_GFX_MAY_MACH_BIKE": {"sheet": "people_may_mach_bike", "w": 32, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_MAY_NORMAL": {"sheet": "people_may_walking", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_MAY_SURFING": {"sheet": "people_may_surfing", "w": 32, "h": 32, "frames": 6},
	"OBJ_EVENT_GFX_MAY_UNDERWATER": {"sheet": "people_may_underwater", "w": 32, "h": 32, "frames": 4},
	"OBJ_EVENT_GFX_MAY_WATERING": {"sheet": "people_may_watering", "w": 32, "h": 32, "frames": 6},
	"OBJ_EVENT_GFX_MEOWTH": {"sheet": "pokemon_old_meowth", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_MEOWTH_DOLL": {"sheet": "dolls_meowth_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_METEORITE": {"sheet": "misc_birth_island_stone_frlg", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_MEW": {"sheet": "pokemon_old_mew", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_MEWTWO": {"sheet": "pokemon_old_mewtwo", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_MG_DELIVERYMAN": {"sheet": "people_mg_deliveryman", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_MISTY": {"sheet": "people_misty", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_MOLTRES": {"sheet": "pokemon_old_moltres", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_MOM": {"sheet": "people_mom", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_MOM_FRLG": {"sheet": "people_mom_frlg", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_MOVING_BOX": {"sheet": "misc_moving_box", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_MR_BRINEYS_BOAT": {"sheet": "misc_mr_brineys_boat", "w": 32, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_MR_FUJI": {"sheet": "people_mr_fuji", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_MUDKIP_DOLL": {"sheet": "dolls_mudkip_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_MYSTERY_GIFT_MAN": {"sheet": "people_mystery_event_deliveryman", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_NIDORAN_F": {"sheet": "pokemon_old_nidoran_f", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_NIDORAN_M": {"sheet": "pokemon_old_nidoran_m", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_NIDORINO": {"sheet": "pokemon_old_nidorino", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_NINJA_BOY": {"sheet": "people_ninja_boy", "w": 16, "h": 16, "frames": 9},
	"OBJ_EVENT_GFX_NOLAND": {"sheet": "people_frontier_brains_noland", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_NORMAN": {"sheet": "people_gym_leaders_norman", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_NURSE": {"sheet": "people_nurse", "w": 16, "h": 32, "frames": 4},
	"OBJ_EVENT_GFX_NURSE_FRLG": {"sheet": "people_nurse_frlg", "w": 16, "h": 32, "frames": 4},
	"OBJ_EVENT_GFX_OLD_AMBER": {"sheet": "misc_old_amber", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_OLD_MAN": {"sheet": "people_old_man", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_OLD_MAN_1": {"sheet": "people_old_man_1", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_OLD_MAN_2": {"sheet": "people_old_man_2", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_OLD_MAN_LYING_DOWN": {"sheet": "people_old_man_lying_down", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_OLD_WOMAN": {"sheet": "people_old_woman", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_OLD_WOMAN_FRLG": {"sheet": "people_old_woman_frlg", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_OMANYTE": {"sheet": "pokemon_old_omanyte", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_PHOEBE": {"sheet": "people_elite_four_phoebe", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_PICHU_DOLL": {"sheet": "dolls_pichu_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_PICNICKER": {"sheet": "people_picnicker", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_PICNICKER_FRLG": {"sheet": "people_picnicker_frlg", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_PIDGEOT": {"sheet": "pokemon_old_pidgeot", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_PIDGEY": {"sheet": "pokemon_old_pidgey", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_PIKACHU": {"sheet": "pokemon_old_pikachu", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_PIKACHU_DOLL": {"sheet": "dolls_pikachu_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_PIKACHU_FRLG": {"sheet": "pokemon_old_pikachu_frlg", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_PIKA_CUSHION": {"sheet": "cushions_pika_cushion", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_POKEDEX": {"sheet": "misc_pokedex", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_POKEFAN_F": {"sheet": "people_pokefan_f", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_POKEFAN_M": {"sheet": "people_pokefan_m", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_POKE_BALL": {"sheet": "misc_ball_poke", "w": 16, "h": 32, "frames": 5},
	"OBJ_EVENT_GFX_POKE_MANIAC_FRLG": {"sheet": "people_poke_maniac_frlg", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_POLICEMAN": {"sheet": "people_policeman", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_POLIWRATH": {"sheet": "pokemon_old_poliwrath", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_POOCHYENA": {"sheet": "pokemon_old_poochyena", "w": 32, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_PROF_BIRCH": {"sheet": "people_prof_birch", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_PROF_OAK": {"sheet": "people_prof_oak", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_PSYCHIC_M": {"sheet": "people_psychic_m", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_PSYDUCK": {"sheet": "pokemon_old_psyduck", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_PUSHABLE_BOULDER": {"sheet": "misc_pushable_boulder", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_PUSHABLE_BOULDER_FRLG": {"sheet": "misc_pushable_boulder_frlg", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_QUINTY_PLUMP": {"sheet": "people_quinty_plump", "w": 32, "h": 32, "frames": 7},
	"OBJ_EVENT_GFX_RAIKOU": {"sheet": "pokemon_old_raikou", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_RAYQUAZA": {"sheet": "pokemon_old_rayquaza_cutscene", "w": 64, "h": 64, "frames": 5},
	"OBJ_EVENT_GFX_RAYQUAZA_STILL": {"sheet": "pokemon_old_rayquaza_still", "w": 64, "h": 64, "frames": 1},
	"OBJ_EVENT_GFX_RED": {"sheet": "people_red", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_RED_BIKE": {"sheet": "people_red_red_bike", "w": 32, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_RED_FIELD_MOVE": {"sheet": "people_red_red_item", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_RED_FISH": {"sheet": "people_red_red_fish", "w": 32, "h": 32, "frames": 12},
	"OBJ_EVENT_GFX_RED_NORMAL": {"sheet": "people_red_red_normal", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_RED_SURF": {"sheet": "people_red_red_surf_run", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_RED_VS_SEEKER": {"sheet": "people_red_red_item", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_RED_VS_SEEKER_BIKE": {"sheet": "people_red_red_vs_seeker_bike", "w": 32, "h": 32, "frames": 6},
	"OBJ_EVENT_GFX_REGICE": {"sheet": "pokemon_old_regi", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_REGIROCK": {"sheet": "pokemon_old_regi", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_REGISTEEL": {"sheet": "pokemon_old_regi", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_REPORTER_F": {"sheet": "people_reporter_f", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_REPORTER_M": {"sheet": "people_reporter_m", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_RICH_BOY": {"sheet": "people_rich_boy", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE": {"sheet": "people_brendan_acro_bike", "w": 32, "h": 32, "frames": 27},
	"OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE": {"sheet": "people_brendan_field_move", "w": 32, "h": 32, "frames": 5},
	"OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE": {"sheet": "people_brendan_mach_bike", "w": 32, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL": {"sheet": "people_brendan_walking", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING": {"sheet": "people_brendan_surfing", "w": 32, "h": 32, "frames": 6},
	"OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE": {"sheet": "people_may_acro_bike", "w": 32, "h": 32, "frames": 27},
	"OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE": {"sheet": "people_may_field_move", "w": 32, "h": 32, "frames": 5},
	"OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE": {"sheet": "people_may_mach_bike", "w": 32, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_RIVAL_MAY_NORMAL": {"sheet": "people_may_walking", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_RIVAL_MAY_SURFING": {"sheet": "people_may_surfing", "w": 32, "h": 32, "frames": 6},
	"OBJ_EVENT_GFX_ROCKER": {"sheet": "people_rocker", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_ROCKET_F": {"sheet": "people_rocket_f", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_ROCKET_M": {"sheet": "people_rocket_m", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN": {"sheet": "people_rooftop_sale_woman", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_ROUND_CUSHION": {"sheet": "cushions_round_cushion", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_ROXANNE": {"sheet": "people_gym_leaders_roxanne", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_RUBY": {"sheet": "misc_ruby", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F": {"sheet": "people_running_triathlete_f", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M": {"sheet": "people_running_triathlete_m", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_SABRINA": {"sheet": "people_sabrina", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_SAILOR": {"sheet": "people_sailor", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_SAILOR_FRLG": {"sheet": "people_sailor_frlg", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_SAPPHIRE": {"sheet": "misc_sapphire", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_SCHOOL_KID_M": {"sheet": "people_school_kid_m", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_SCIENTIST": {"sheet": "people_scientist", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_SCIENTIST_1": {"sheet": "people_scientist_1", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_SCIENTIST_2": {"sheet": "people_scientist_2", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_SCOTT": {"sheet": "people_scott", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_SEAGALLOP": {"sheet": "misc_seagallop", "w": 64, "h": 64, "frames": 1},
	"OBJ_EVENT_GFX_SEEDOT_DOLL": {"sheet": "dolls_seedot_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_SEEL": {"sheet": "pokemon_old_seel", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_SIDNEY": {"sheet": "people_elite_four_sidney", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_SIGN": {"sheet": "misc_sign", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_SKITTY": {"sheet": "pokemon_old_skitty", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_SKITTY_DOLL": {"sheet": "dolls_skitty_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_SLOWBRO": {"sheet": "pokemon_old_slowbro", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_SLOWPOKE": {"sheet": "pokemon_old_slowpoke", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_SMOOCHUM_DOLL": {"sheet": "dolls_smoochum_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_SNORLAX": {"sheet": "pokemon_old_snorlax", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_SPEAROW": {"sheet": "pokemon_old_spearow", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_SPENSER": {"sheet": "people_frontier_brains_spenser", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_SPIN_CUSHION": {"sheet": "cushions_spin_cushion", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_SS_ANNE": {"sheet": "misc_ss_anne", "w": 128, "h": 64, "frames": 1},
	"OBJ_EVENT_GFX_SS_TIDAL": {"sheet": "misc_ss_tidal", "w": 96, "h": 40, "frames": 1},
	"OBJ_EVENT_GFX_STEVEN": {"sheet": "people_steven", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_SUBMARINE_SHADOW": {"sheet": "misc_submarine_shadow", "w": 88, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_SUDOWOODO": {"sheet": "pokemon_old_sudowoodo_tree", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_SUICUNE": {"sheet": "pokemon_old_suicune", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_SWABLU_DOLL": {"sheet": "dolls_swablu_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_SWIMMER_F": {"sheet": "people_swimmer_f", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_SWIMMER_F_LAND": {"sheet": "people_swimmer_f_land", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_SWIMMER_F_WATER": {"sheet": "people_swimmer_f_water", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_SWIMMER_M": {"sheet": "people_swimmer_m", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_SWIMMER_M_LAND": {"sheet": "people_swimmer_m_land", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_SWIMMER_M_WATER": {"sheet": "people_swimmer_m_water", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_TATE": {"sheet": "people_gym_leaders_tate", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_TEACHY_TV_HOST": {"sheet": "people_teachy_tv_host", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_TEALA": {"sheet": "people_teala", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_TOGEPI_DOLL": {"sheet": "dolls_togepi_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_TORCHIC_DOLL": {"sheet": "dolls_torchic_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_TOTODILE_DOLL": {"sheet": "dolls_totodile_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_TOWN_MAP": {"sheet": "misc_town_map", "w": 32, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_TRAINER_TIPS": {"sheet": "misc_wooden_sign", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_TRAINER_TOWER_DUDE": {"sheet": "people_trainer_tower_dude", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_TREECKO_DOLL": {"sheet": "dolls_treecko_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_TRICK_HOUSE_STATUE": {"sheet": "misc_statue", "w": 16, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_TRUCK": {"sheet": "misc_truck", "w": 48, "h": 48, "frames": 1},
	"OBJ_EVENT_GFX_TUBER_F": {"sheet": "people_tuber_f", "w": 16, "h": 16, "frames": 9},
	"OBJ_EVENT_GFX_TUBER_F_FRLG": {"sheet": "people_tuber_f", "w": 16, "h": 16, "frames": 9},
	"OBJ_EVENT_GFX_TUBER_M": {"sheet": "people_tuber_m", "w": 16, "h": 16, "frames": 9},
	"OBJ_EVENT_GFX_TUBER_M_LAND": {"sheet": "people_tuber_m_land", "w": 16, "h": 16, "frames": 10},
	"OBJ_EVENT_GFX_TUBER_M_SWIMMING": {"sheet": "people_tuber_m_swimming", "w": 16, "h": 16, "frames": 9},
	"OBJ_EVENT_GFX_TUBER_M_WATER": {"sheet": "people_tuber_m_water", "w": 16, "h": 16, "frames": 10},
	"OBJ_EVENT_GFX_TUCKER": {"sheet": "people_frontier_brains_tucker", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_TWIN": {"sheet": "people_twin", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_UNION_ROOM_NURSE": {"sheet": "people_union_room_attendant", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_UNION_ROOM_RECEPTIONIST": {"sheet": "people_union_room_receptionist", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_UNUSED_MAGNEMITE_DOLL": {"sheet": "dolls_unused_magnemite_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_UNUSED_NATU_DOLL": {"sheet": "dolls_unused_natu_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_UNUSED_PIKACHU_DOLL": {"sheet": "dolls_unused_pikachu_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_UNUSED_PORYGON2_DOLL": {"sheet": "dolls_unused_porygon2_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_UNUSED_SQUIRTLE_DOLL": {"sheet": "dolls_unused_squirtle_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_UNUSED_WOOPER_DOLL": {"sheet": "dolls_unused_wooper_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_VIGOROTH_CARRYING_BOX": {"sheet": "pokemon_old_vigoroth_mover", "w": 32, "h": 32, "frames": 5},
	"OBJ_EVENT_GFX_VIGOROTH_FACING_AWAY": {"sheet": "pokemon_old_vigoroth_mover", "w": 32, "h": 32, "frames": 5},
	"OBJ_EVENT_GFX_VOLTORB": {"sheet": "pokemon_old_voltorb", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_WALLACE": {"sheet": "people_wallace", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_WALLY": {"sheet": "people_wally", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_WATER_CUSHION": {"sheet": "cushions_water_cushion", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_WATTSON": {"sheet": "people_gym_leaders_wattson", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_WIGGLYTUFF": {"sheet": "pokemon_old_wigglytuff", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_WINGULL": {"sheet": "pokemon_old_wingull", "w": 16, "h": 16, "frames": 6},
	"OBJ_EVENT_GFX_WINONA": {"sheet": "people_gym_leaders_winona", "w": 16, "h": 32, "frames": 3},
	"OBJ_EVENT_GFX_WOMAN_1": {"sheet": "people_woman_1", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_WOMAN_1_FRLG": {"sheet": "people_woman_1_frlg", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_WOMAN_2": {"sheet": "people_woman_2", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_WOMAN_2_FRLG": {"sheet": "people_woman_2_frlg", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_WOMAN_3": {"sheet": "people_woman_3", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_WOMAN_3_FRLG": {"sheet": "people_woman_3_frlg", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_WOMAN_4": {"sheet": "people_woman_4", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_WOMAN_5": {"sheet": "people_woman_5", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_WORKER_F": {"sheet": "people_worker_f", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_WORKER_M": {"sheet": "people_worker_m", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_WYNAUT_DOLL": {"sheet": "dolls_wynaut_doll", "w": 16, "h": 16, "frames": 1},
	"OBJ_EVENT_GFX_YOUNGSTER": {"sheet": "people_youngster", "w": 16, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_YOUNGSTER_FRLG": {"sheet": "people_youngster_frlg", "w": 16, "h": 32, "frames": 10},
	"OBJ_EVENT_GFX_ZAPDOS": {"sheet": "pokemon_old_zapdos", "w": 32, "h": 32, "frames": 1},
	"OBJ_EVENT_GFX_ZIGZAGOON_1": {"sheet": "pokemon_old_enemy_zigzagoon", "w": 32, "h": 32, "frames": 9},
	"OBJ_EVENT_GFX_ZIGZAGOON_2": {"sheet": "pokemon_old_zigzagoon", "w": 16, "h": 16, "frames": 3},
	"OBJ_EVENT_GFX_ZIGZAG_CUSHION": {"sheet": "cushions_zigzag_cushion", "w": 16, "h": 16, "frames": 1},
}


## Sheet path for a graphics id, falling back the way source does.
static func sheet_path(graphics_id: String) -> String:
	var e: Dictionary = BY_ID.get(graphics_id, BY_ID.get(FALLBACK_ID, {}))
	if e.is_empty():
		return ""
	return SHEET_DIR + str(e["sheet"]) + ".png"


## Frame size for a graphics id. Sizes are NOT uniform — 16x32 dominates
## but 16x16 and 32x16 are both real — so a renderer must read this
## rather than assuming.
static func frame_size(graphics_id: String) -> Vector2i:
	var e: Dictionary = BY_ID.get(graphics_id, BY_ID.get(FALLBACK_ID, {}))
	if e.is_empty():
		return Vector2i(16, 32)
	return Vector2i(int(e["w"]), int(e["h"]))


## How many frames this id's sheet actually holds.
##
## Read it before indexing a step frame: not every sheet has one.
static func frame_count(graphics_id: String) -> int:
	var e: Dictionary = BY_ID.get(graphics_id, BY_ID.get(FALLBACK_ID, {}))
	if e.is_empty():
		return 1
	return int(e["frames"])


## Is this an id this project can actually draw?
##
## OBJ_EVENT_GFX_VAR_0..F are absent BY DESIGN: source resolves them at
## runtime through VarGetObjectEventGraphicsId, so the sprite is chosen by
## a script variable and cannot be pulled. 44 exist region-wide. They fall
## back until M27G can answer them.
static func is_known(graphics_id: String) -> bool:
	return BY_ID.has(graphics_id)
