class_name BattlerCoords
extends RefCounted

## Battler screen coordinates, ported verbatim from source.
##
## ⚠️ **GENERATED BY `scripts/gen_battler_coords.py` -- DO NOT HAND-EDIT.**
## Re-run the generator instead; it also places the six sprite nodes in
## `battle_screen_singles.tscn` / `battle_screen_doubles.tscn` from this same
## parse, which is what keeps the table and the scenes from drifting apart.
##
## Source: `sBattlerCoords` (`src/battle_anim_mons.c`). The values are GBA
## screen pixels on a 240x160 canvas, and are the sprite's CENTRE.
##
## ⚠️ **SINGLES USES ONLY THE TWO `_LEFT` POSITIONS.** The `_RIGHT` entries in
## the singles table are real data and are deliberately unused here -- source
## reaches them through move animations that borrow a second slot, not through
## battler placement. Placing a singles battler at a `_RIGHT` coordinate would
## look plausible and be wrong.


## The canvas these coordinates are expressed against.
const GBA_SCREEN := Vector2(240.0, 160.0)

## A battler sprite is 64x64 on hardware.
const GBA_SPRITE_SIZE := 64


const SINGLES := {
	"B_POSITION_PLAYER_LEFT": Vector2i(72, 80),
	"B_POSITION_OPPONENT_LEFT": Vector2i(176, 40),
	"B_POSITION_PLAYER_RIGHT": Vector2i(48, 40),
	"B_POSITION_OPPONENT_RIGHT": Vector2i(112, 80),
}

const DOUBLES := {
	"B_POSITION_PLAYER_LEFT": Vector2i(32, 80),
	"B_POSITION_OPPONENT_LEFT": Vector2i(200, 40),
	"B_POSITION_PLAYER_RIGHT": Vector2i(90, 84),
	"B_POSITION_OPPONENT_RIGHT": Vector2i(152, 32),
}


## The point anchor for a battler, as a fraction of the canvas.
##
## ⚠️ **Anchors, not pixels, and that is the whole point of expressing it this
## way:** a fraction survives a canvas change untouched, while a pixel offset
## is a constant tuned against one resolution. This project has changed canvas
## twice (16:9 -> 4:3 -> 3:2), and each time the pixel-placed nodes drifted
## while the anchored ones did not.
static func anchor_for(mode: Dictionary, position_key: String) -> Vector2:
	var c: Vector2i = mode.get(position_key, Vector2i.ZERO)
	return Vector2(float(c.x) / GBA_SCREEN.x, float(c.y) / GBA_SCREEN.y)


## Half the sprite box in pixels, at a given uniform GBA->canvas scale.
static func half_box(scale: float) -> float:
	return GBA_SPRITE_SIZE * scale * 0.5
