class_name HealthboxCoords
extends RefCounted

## Healthbox screen geometry, derived from source.
##
## ⚠️ **GENERATED BY `scripts/gen_healthbox_coords.py` -- DO NOT HAND-EDIT.**
## Re-run the generator instead; it also places the six panel nodes in
## `battle_screen_singles.tscn` / `battle_screen_doubles.tscn` from the same
## parse, which is what keeps the table and the scenes from drifting apart.
##
## Each Rect2 is the REAL ART's rectangle in GBA screen pixels on a 240x160
## canvas -- already resolved from `sBattlerHealthboxCoords`
## (`src/battle_interface.c`, the CENTRE of the left of two 64-wide sprites)
## plus the measured inset of the art inside its own OAM sheet. Consumers
## multiply by the canvas scale and nothing else.
##
## ⚠️ **HEIGHT IS NOT MATCHED, AND THAT IS DELIBERATE.** This project draws the
## Emerald UI Pack's redrawn box art, whose aspect differs from source's by
## 5-15%. The generator matches WIDTH exactly and lets height fall out, rather
## than distorting the art with a non-uniform scale -- see the generator's own
## header for the measurements behind that call.


## The canvas these coordinates are expressed against.
const GBA_SCREEN := Vector2(240.0, 160.0)

## One healthbox sprite; a box is two of these side by side.
const GBA_SPRITE_WIDTH := 64


const SINGLES := {
	"B_POSITION_PLAYER_LEFT": Rect2(127, 58, 103, 36),
	"B_POSITION_OPPONENT_LEFT": Rect2(13, 16, 100, 28),
}

const DOUBLES := {
	"B_POSITION_PLAYER_LEFT": Rect2(128, 62, 100, 25),
	"B_POSITION_PLAYER_RIGHT": Rect2(140, 87, 100, 25),
	"B_POSITION_OPPONENT_LEFT": Rect2(13, 5, 100, 25),
	"B_POSITION_OPPONENT_RIGHT": Rect2(1, 30, 100, 25),
}


## The art's rectangle in canvas pixels at a given uniform GBA->canvas scale.
static func rect_for(mode: Dictionary, position_key: String, scale: float) -> Rect2:
	var r: Rect2 = mode.get(position_key, Rect2())
	return Rect2(r.position * scale, r.size * scale)


## The point anchor for a healthbox's top-left, as a fraction of the canvas.
##
## Anchors rather than pixels, for the reason `BattlerCoords.anchor_for` gives:
## a fraction survives a canvas change untouched.
static func anchor_for(mode: Dictionary, position_key: String) -> Vector2:
	var r: Rect2 = mode.get(position_key, Rect2())
	return r.position / GBA_SCREEN
