extends Node

# [Back-sprite Y-offset fix, 2026-08-10] Covers the fix for a real, reported
# bug: Bulbasaur/Charmander's back sprites rendered with their bottom edge
# visibly cut off in battle while Squirtle looked fine — because only the
# OPPONENT (front) sprite bottom-anchored per species via
# SpriteRegistry.get_front_y_offset(); the PLAYER (back) sprite used one
# static .tscn-authored offset for every species regardless of how much
# transparent padding that species' own 64x64 art carries.
#
# Mirrors the reasoning already established for the front-sprite mechanism
# (see _apply_bottom_anchored_front_sprite's own doc comment) — this suite
# is deliberately a bare-instance test (BattleScreenShared.new(), no live
# scene tree), matching the precedent already set for testing
# _show_trainer_intro() the same way.

var _pass := 0
var _fail := 0


func _ready() -> void:
	_test_back_y_offsets_match_source()
	_test_apply_bottom_anchored_back_sprite_shifts_by_species()
	_test_discriminator_different_species_different_shift()
	_test_texture_is_set_to_the_species_back_sprite()

	var total := _pass + _fail
	print("back_sprite_y_offset_test: %d/%d passed" % [_pass, total])
	if _fail > 0:
		print("FAILED")
	get_tree().quit(0 if _fail == 0 else 1)


func _chk(label: String, cond: bool) -> void:
	if cond:
		_pass += 1
	else:
		_fail += 1
		print("FAIL  " + label)


# Real values, generated by gen_sprite_y_offsets.py directly from source's
# own .backPicYOffset field — spot-checked against the exact figures the
# original bug report's own investigation measured.
func _test_back_y_offsets_match_source() -> void:
	_chk("Bulbasaur (dex 1) backPicYOffset == 16", SpriteRegistry.get_back_y_offset(1) == 16)
	_chk("Charmander (dex 4) backPicYOffset == 14", SpriteRegistry.get_back_y_offset(4) == 14)
	_chk("Squirtle (dex 7) backPicYOffset == 14", SpriteRegistry.get_back_y_offset(7) == 14)
	_chk("an unresolvable dex degrades to 0 (no padding assumed), matching " +
			"get_front_y_offset's own convention",
			SpriteRegistry.get_back_y_offset(9999) == 0)


# Same formula as _apply_bottom_anchored_front_sprite: shift = backPicYOffset
# * (box_width / 64.0), added to both the base top and base bottom offsets.
func _test_apply_bottom_anchored_back_sprite_shifts_by_species() -> void:
	var bs := BattleScreenShared.new()
	var rect := TextureRect.new()
	rect.offset_left = -178.5
	rect.offset_right = 178.5  # width = 357 -> scale = 357/64

	bs._apply_bottom_anchored_back_sprite(rect, 1, 0.0, 100.0)  # Bulbasaur

	var scale := 357.0 / 64.0
	var expected_shift := 16 * scale
	_chk("offset_top shifted by backPicYOffset * scale",
			is_equal_approx(rect.offset_top, 0.0 + expected_shift))
	_chk("offset_bottom shifted by backPicYOffset * scale",
			is_equal_approx(rect.offset_bottom, 100.0 + expected_shift))

	rect.free()
	bs.free()


# ⚠️ THE DISCRIMINATOR THAT PROVES THE ORIGINAL BUG: before this fix, EVERY
# species produced the identical offset_top/offset_bottom (the .tscn's one
# static value), since nothing ever read get_back_y_offset() for the player
# sprite. Bulbasaur (16) and Squirtle (14) must now produce DIFFERENT shifts.
func _test_discriminator_different_species_different_shift() -> void:
	var bs := BattleScreenShared.new()

	var rect1 := TextureRect.new()
	rect1.offset_left = -178.5
	rect1.offset_right = 178.5
	bs._apply_bottom_anchored_back_sprite(rect1, 1, 0.0, 100.0)  # Bulbasaur, offset=16

	var rect2 := TextureRect.new()
	rect2.offset_left = -178.5
	rect2.offset_right = 178.5
	bs._apply_bottom_anchored_back_sprite(rect2, 7, 0.0, 100.0)  # Squirtle, offset=14

	_chk("discriminator: Bulbasaur and Squirtle produce DIFFERENT offset_top " +
			"shifts (the exact species pair from the original bug report)",
			not is_equal_approx(rect1.offset_top, rect2.offset_top))
	_chk("both still resolve to the SAME base_bottom-relative anchor once their " +
			"own padding is cancelled out (same base_top/base_bottom args)",
			is_equal_approx(rect1.offset_top - rect1.offset_bottom,
					rect2.offset_top - rect2.offset_bottom))

	rect1.free()
	rect2.free()
	bs.free()


func _test_texture_is_set_to_the_species_back_sprite() -> void:
	var bs := BattleScreenShared.new()
	var rect := TextureRect.new()
	rect.offset_left = -178.5
	rect.offset_right = 178.5
	bs._apply_bottom_anchored_back_sprite(rect, 4, 0.0, 100.0)  # Charmander
	_chk("the rect's texture is actually set (not left null)", rect.texture != null)
	rect.free()
	bs.free()
