class_name MoveNameMap
extends RefCounted

# [M23.4] Resolves the "MOVE_TACKLE"-style constant-name strings
# PokemonRegistry.get_learnable_moves()/get_learnset() deal in (sourced from
# learnsets.json/all_learnables.json) into the numeric move IDs every other
# part of this project uses (MoveRegistry, PokemonFactory, BattlePokemon).
#
# Backed by data/move_name_to_id.json, generated by
# scripts/gen_move_name_map.py directly from the canonical reference enum
# (reference/pokeemerald_expansion/include/constants/moves.h) — see that
# script's own header comment for the full parsing rationale (sequential
# auto-increment resolution, alias entries, etc.). Re-run the generator and
# re-import if a future move ever needs a name added to the reference enum
# that isn't already covered (956 entries as of this writing — comfortably
# covers every move referenced by any of this project's own species data).
#
# Static/lazy-loaded, mirroring PokemonFactory's own static-method-only
# shape — this is a pure lookup utility, not a Node, and never needs more
# than one copy of the parsed map alive at once.

const _MAP_PATH := "res://data/move_name_to_id.json"

static var _name_to_id: Dictionary = {}
static var _loaded: bool = false


static func _ensure_loaded() -> void:
	if _loaded:
		return
	_loaded = true
	var file := FileAccess.open(_MAP_PATH, FileAccess.READ)
	if file == null:
		push_error("MoveNameMap: failed to open %s (error %d)" % [_MAP_PATH, FileAccess.get_open_error()])
		return
	var parsed = JSON.parse_string(file.get_as_text())
	file.close()
	if typeof(parsed) == TYPE_DICTIONARY:
		_name_to_id = parsed


# Returns the numeric move ID for a "MOVE_XXX" constant-name string, or -1
# if the name isn't recognized. [JSON float gotcha] JSON.parse_string
# returns numeric values as float — explicitly int()-cast here, matching
# this project's own standing convention (see e.g. PokemonFactory.
# build_species's own doc comment for the same gotcha).
static func id_for_name(move_name: String) -> int:
	_ensure_loaded()
	if not _name_to_id.has(move_name):
		return -1
	return int(_name_to_id[move_name])
